# Generated by Django 4.1.4 on 2022-12-10 21:36

import django.db.models.deletion
from django.db import migrations, models

import financica.lib.database.fields.files


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        help_text=(
                            "Stripe ID of the receipt (rcpt_*, invrc_* or pmtrc_*)"
                        ),
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("rcpt", "Charge Receipt"),
                            ("invrc", "Invoice Receipt"),
                            ("pmtrc", "Payment Receipt"),
                            ("rfdrc", "Refund Receipt"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "livemode",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the object is in live or test mode",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        help_text="Language the receipt is in", max_length=16
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        db_index=True,
                        help_text="End-user visible receipt number",
                        max_length=128,
                    ),
                ),
                (
                    "account_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text=(
                            "Stripe ID of the account that owns the receipt (acct_*)"
                        ),
                        max_length=128,
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text=(
                            "Stripe ID of the customer issued the receipt (cus_*)"
                        ),
                        max_length=128,
                    ),
                ),
                (
                    "invoice_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stripe ID of the original invoice (in_*)",
                        max_length=128,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="End-user visible invoice number",
                        max_length=128,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "receipt_html",
                    financica.lib.database.fields.files.FileAttachmentField(
                        blank=True,
                        help_text="The receipt, as HTML",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stripe_html_receipts",
                        to="files.file",
                    ),
                ),
                (
                    "receipt_pdf",
                    financica.lib.database.fields.files.FileAttachmentField(
                        blank=True,
                        help_text="The receipt, as PDF (sometimes unavailable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stripe_pdf_receipts",
                        to="files.file",
                    ),
                ),
            ],
        ),
    ]
